spring.application.name=MVC-jdbc
spring.datasource.url=XXX
spring.datasource.username=XXX
spring.datasource.password=XXX
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.html
spring.flyway.enabled=true
spring.flyway.locations=classpath:sql/migrations